from enum import StrEnum


class ErrorCode(StrEnum):
    AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR'
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR'
    VALIDATION_ERROR = 'VALIDATION_ERROR'
